# Generated by Django 5.2.8 on 2025-11-24 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='system_response',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Resposta do Sistema'),
        ),
    ]
